Updated pull request
eclipse-volttron/eclipse-volttron.github.io pull request #15
Opened 2024-09-16 19:23 UTC by dominrios

Changes made to the For Developers page, anchor links for the accomplishments, small accomplishment blurbs for several market pages. Testing images for the Accomplishments page

2024-09-17 00:06 UTC, craig8 requested changes

2024-09-17 00:06 UTC, craig8 commented on content/Developers.md
> +The Eclipse VOLTTRON development team supports the wider user community with numerous resources in an effort to maximize transparency and simplify working with the platform. The project is hosted on
This should be what the old one was, it just needed the s in docs.  The en/latest is there for us to modify and send them to a different place based upon language preferences and default version (which we can change).

2024-09-23 23:28 UTC, dominrios reviewed
added an s in docs and removed the excess

2024-09-23 23:43 UTC, craig8 approved these changes

2024-09-23 23:43 UTC, merged